- name: General | SSMTP packages
  apt: name=ssmtp state=present

- name: SSMTP | Configure ssmtp.conf
  template: 
    src: etc-ssmtp-ssmtp-conf
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    mode: 0644
  tags:
    - configuration

- name: SSMTP | Configure revaliases
  template: 
    src: etc-ssmtp-revaliases
    dest: /etc/ssmtp/revaliases
    owner: root
    mode: 0644
  tags:
    - configuration