- name: General | Install Apache packages
  apt: "name={{ item }} state=present"
  with_items:
    - php5
    - apache2
    - php5-mysql
    - php-apc
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - php5-curl
    - sendmail
    - unzip

- name: Apache | Enable php modules
  apache2_module: "name={{ item }} state=present"
  with_items:
    - php5
    - proxy
    - proxy_http
    - headers
    - rewrite
    - dir

- name: Apache | Remove default site
  file: path={{ item }} state=absent
  with_items:
    - /etc/apache2/sites-enabled/000-default.conf
    - /etc/apache2/sites-enabled/000-default

- name: Apache | Configuration file /etc/php5/apache2/php.ini
  template: 
    src: php.ini
    dest: /etc/php5/apache2/php.ini
    owner: root
    mode: 0755
  tags:
    - configuration