- name: General | Install MySQL packages
  apt: "name={{ item }} state=present"
  with_items:
    - mysql-server-5.5
    - mysql-client-5.5
    - libmysqlclient-dev
    - python-mysqldb
  when: not {{skip_install}}

- name: MySQL | Configuration file /etc/mysql/my.cnf
  template: 
    src: etc-mysql-my-cnf
    dest: /etc/mysql/my.cnf
    owner: root
    mode: 0600

- name: MySQL | Configuration file /root/.my.cnf
  template: 
    src: root-my-cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: MySQL | Start the MySQL service
  service: 
    name: mysql 
    state: started

- name: MySQL | Update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}" 
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ server_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 

- name: MySQL | Remove the MySQL test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent
